/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.ClothingRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.FoodClothing.Cloth;
import Business.FoodClothing.ClothInventory;


import Business.Homeless.Homeless;
import Business.Homeless.HomelessDirectory;
import Business.Network.Network;
import Business.Organization.ClothingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import userinterface.MainJFrame;
import static userinterface.MainJFrame.passwordField;

/**
 *
 * @author mahes
 */
public class ClothingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClothingWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ClothingOrganization clothingOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HomelessDirectory homelessDirectory;
    private Homeless homeless;
    private EcoSystem business;
    private Network network;
    private ClothInventory clothinginventory;
   
    
    public ClothingWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, ClothInventory clothinventory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.clothingOrganization = (ClothingOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
        this.homelessDirectory = new HomelessDirectory();
        this.clothinginventory=clothinventory;
        populateTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clothTbl = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        donateBtn1 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel1.setText("Shelter:");

        quantityTxt.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel2.setText("Location:");

        updateBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel3.setText("Donated On:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel6.setText("Quantity Provided:");

        locationTxt.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N

        clothTbl.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        clothTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Shelter", "Location", "DonatedOn", "Quantity"
            }
        ));
        clothTbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        clothTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clothTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clothTbl);

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cambridge", "Boston", "Wrentham", "New York", "Park Drive" }));

        donateBtn1.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        donateBtn1.setText("Donate");
        donateBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        donateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtn1ActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(locationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(donateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(donateBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clothTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clothTblMouseClicked

        int i = clothTbl.getSelectedRow();
        TableModel model = clothTbl.getModel();
        jComboBox1.setSelectedItem(model.getValueAt(i,0).toString());
        locationTxt.setText(model.getValueAt(i,1).toString());

        quantityTxt.setText(model.getValueAt(i,2).toString());
        date.setDateFormatString(model.getValueAt(i,3).toString());
        
    }//GEN-LAST:event_clothTblMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = clothTbl.getSelectedRow();

        if (selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to edit!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) clothTbl.getModel();
        Cloth selectedDetail = (Cloth) model.getValueAt(selectedRowIndex,0);


        String shelter = jComboBox1.toString();
        String location = locationTxt.getText();
        int quantity = Integer.parseInt(quantityTxt.getText());
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String donatedOn = dformat.format(date.getDate());
        
        int index=clothinginventory.getClothinventory().indexOf(selectedDetail);
        Cloth cloth= clothinginventory.updateInventory(index, selectedDetail);

        cloth.setShelter(shelter);
        cloth.setLocation(location);
        cloth.setQuantity(quantity);
        cloth.setDonatedon(donatedOn);
        cloth.setProvidedby("");
        
     
       
    }//GEN-LAST:event_updateBtnActionPerformed

    private void donateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtn1ActionPerformed
        // TODO add your handling code here:
        
        String shelter = jComboBox1.toString();
      
        String location = locationTxt.getText();
        int quantity = Integer.parseInt(quantityTxt.getText());
        
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String donatedOn = dformat.format(date.getDate());
        
        
        Cloth cloth = clothinginventory.addToInventory();
        cloth.setShelter(shelter);
        cloth.setLocation(location);
        cloth.setQuantity(quantity);
        cloth.setDonatedon(donatedOn);
    }//GEN-LAST:event_donateBtn1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable clothTbl;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton donateBtn1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void populateTbl() {
    MainJFrame mainframe = new MainJFrame();
       String userName = mainframe.userNameJTextField.getText();
       char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);
       
       UserAccount userAccount=business.getUserAccountDirectory().authenticateUser(userName, password);
        
        DefaultTableModel model = (DefaultTableModel) clothTbl.getModel();
        model.setRowCount(0);
        
        
        for (Cloth cloth : clothinginventory.getClothinventory())
        {
            if(cloth.getProvidedby().equals(userAccount.getUsername()))
            {
            Object[] row = new Object[4];
            row[0]=cloth.getShelter();
            row[1]=cloth.getLocation();
            row[1]=cloth.getDonatedon();
            row[1]=cloth.getQuantity();
            
            model.addRow(row);
            
            }
        }
       
    }
}
