/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ClothingRole;

import HMS.NetworkDirectory;
import HMS.Enterprise.Enterprise;
import HMS.FoodClothing.Cloth;
import HMS.FoodClothing.ClothInventory;
import HMS.Homeless.Homeless;
import HMS.Homeless.HomelessDirectory;
import HMS.Network.Network;
import HMS.Organization.ClothingOrganization;
import HMS.Organization.Organization;
import HMS.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author mahes
 */
public class ClothingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClothingWorkAreaJPanel
     */
    private JPanel userProcessContainer;
   // private ClothingOrganization clothingOrganization;
    private Enterprise enterprise;
   // private UserAccount userAccount;
  //  private HomelessDirectory homelessDirectory;
   // private Homeless homeless;
    private NetworkDirectory business;
   // private Network network;
    private ClothInventory clothinginventory;
    private String username;
    
    public ClothingWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, NetworkDirectory business, ClothInventory clothinventory, String username) {
        initComponents();
        //this.userProcessContainer = userProcessContainer;
        //this.userAccount = account;
        //this.clothingOrganization = (ClothingOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
   //     this.homelessDirectory = new HomelessDirectory();
        this.clothinginventory=clothinventory;
        this.username=username;
        populateTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clothTbl = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        donateBtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setText("Shelter:");

        quantityTxt.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setText("Location:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setText("Donated On:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel6.setText("Quantity Provided:");

        locationTxt.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N

        clothTbl.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        clothTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Shelter", "Location", "DonatedOn", "Quantity"
            }
        ));
        clothTbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        clothTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clothTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clothTbl);

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cambridge", "Boston", "Wrentham", "New York", "Park Drive" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        date.setBackground(new java.awt.Color(255, 255, 255));

        donateBtn1.setBackground(new java.awt.Color(0, 0, 0));
        donateBtn1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        donateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        donateBtn1.setText("Donate");
        donateBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        donateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtn1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/clothes-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(614, 614, 614)
                        .addComponent(donateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(333, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(donateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clothTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clothTblMouseClicked

        int i = clothTbl.getSelectedRow();
        TableModel model = clothTbl.getModel();
        jComboBox1.setSelectedItem(model.getValueAt(i,0).toString());
        locationTxt.setText(model.getValueAt(i,1).toString());

        quantityTxt.setText(model.getValueAt(i,2).toString());
        date.setDateFormatString(model.getValueAt(i,3).toString());
        
    }//GEN-LAST:event_clothTblMouseClicked

    private void donateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtn1ActionPerformed
        // TODO add your handling code here:
        
        String shelter = jComboBox1.getSelectedItem().toString();
      
        String location = locationTxt.getText();
        int quantity = Integer.parseInt(quantityTxt.getText());
        
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String donatedOn = dformat.format(date.getDate());
        
        
     //   for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
       //{
           
         //      if(organization.getName().contains("Cloth Organization"))
           // {
           try{
              // JOptionPane.showMessageDialog(null, enterprise);
                  clothinginventory.addToInventory(shelter, location, quantity, username, donatedOn);
                      // organization.getFoodinventory().addToInventory(shelter, location, quantity, username, donatedOn);
                       JOptionPane.showMessageDialog(null, quantity +" units of cloth have been donated. Thank You!");
                   populateTbl();
              //     organization.getFoodinventory().addToInventory(shelter,location,quantity, username, donatedOn);
            //       JOptionPane.showMessageDialog(null, "Added");
                 //  populateTbl();
       //       }
       //}
      
           }
           catch(NullPointerException e)
           {
               JOptionPane.showMessageDialog(null, e);
           }
            //}
       //}
    // org.getFoodinventory().addToInventory(shelter,location,quantity, username, donatedOn);
      // JOptionPane.showMessageDialog(null, "Added");
     //  JOptionPane.showMessageDialog(null, org);
      // populateTbl();
       
        
        
        
        /*
        Cloth cloth = clothinginventory.addToInventory();
        cloth.setShelter(shelter);
        cloth.setLocation(location);
        cloth.setQuantity(quantity);
        cloth.setDonatedon(donatedOn);
        */


    }//GEN-LAST:event_donateBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clothTbl;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton donateBtn1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField quantityTxt;
    // End of variables declaration//GEN-END:variables

    private void populateTbl() {
    
        DefaultTableModel model = (DefaultTableModel) clothTbl.getModel();
        model.setRowCount(0);
        
        
       //   for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
       //{
           
         //      if(organization.getName().contains("Cloth Organization"))
           //   {
                   for (Cloth cloth : clothinginventory.getClothinventory())
        {
            if(cloth.getProvidedby().equals(username))
            {
            Object[] row = new Object[4];
            row[0]=cloth.getShelter();
            row[1]=cloth.getLocation();
            row[2]=cloth.getDonatedon();
            row[3]=cloth.getQuantity();
            
            model.addRow(row);
            
            }
        //}
       
       
    //}
      //        }
       
    
    }

}
       
}
