/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NGOSupervisorRole;

import HMS.FoodClothing.Cloth;
import HMS.FoodClothing.ClothInventory;
import HMS.FoodClothing.Food;
import HMS.FoodClothing.FoodInventory;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author mahes
 */
public class NGOCostSaved extends javax.swing.JPanel {

    /**
     * Creates new form NGOCostSaved
     */
    private FoodInventory foodinventory;
    private ClothInventory clothinventory;
    public NGOCostSaved(FoodInventory foodinventory, ClothInventory clothinventory) {
        initComponents();
        this.foodinventory=foodinventory;
        this.clothinventory=clothinventory;
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piePlot1 = new org.jfree.chart.plot.PiePlot();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton1)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int foodsum=0;
        for(Food food : foodinventory.getTotalCost())
        {
            foodsum = foodsum + food.getTotalCost();
            
        }
        
        int clothsum=0;
        for(Cloth cloth : clothinventory.getTotalCostSaved())
        {
            clothsum = clothsum + cloth.getSavedCost();
            
        }
        
        DefaultPieDataset piedataset = new DefaultPieDataset();
        piedataset.setValue("Cost saved on Food", foodsum );
        piedataset.setValue("Cost saved on Clothing",clothsum);
        
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", piedataset,true,true,true);
        PiePlot3D P = (PiePlot3D)chart.getPlot();
        //P.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,500);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private org.jfree.chart.plot.PiePlot piePlot1;
    // End of variables declaration//GEN-END:variables
}
