/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FoodRole;

import HMS.NetworkDirectory;
import HMS.Enterprise.Enterprise;
import HMS.FoodClothing.Food;
import HMS.FoodClothing.FoodInventory;
import HMS.Organization.Organization;
//import Business.Homeless.Homeless;
//import Business.Homeless.HomelessDirectory;
//import Business.Network.Network;
//import Business.Organization.FoodOrganization;
//import Business.Organization.Organization;
import HMS.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahes
 */
public class FoodWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    //private FoodOrganization foodOrganization;
    private Enterprise enterprise;
   // private UserAccount userAccount;
    //private HomelessDirectory homelessDirectory;
    //private Homeless homeless;
    private NetworkDirectory business;
    //private Network network;
    private FoodInventory foodinventory;
    private String username;
    private Organization org;
    public FoodWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,Organization organization, NetworkDirectory business, FoodInventory foodinventory, String username) {
        initComponents();
        //this.userProcessContainer = userProcessContainer;
        //this.userAccount = account;
        ///this.foodOrganization = (FoodOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
        this.username=username;
        //this.homelessDirectory = new HomelessDirectory();
      this.foodinventory= foodinventory;
     // this.org=organization;
      
      populateTbl();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setText("Shelter:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setText("Location:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setText("Donated On:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel6.setText("Quantity Provided:");

        locationTxt.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N

        quantityTxt.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Donate");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cambridge", "Boston", "Wrentham", "New York", "Park Drive" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        foodTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Shelter", "Location", "Donated On", "Quantity Provided"
            }
        ));
        jScrollPane2.setViewportView(foodTbl);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/food-removebg-preview.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locationTxt)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantityTxt)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(784, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String shelter = jComboBox1.getSelectedItem().toString() ;
      
        String location = locationTxt.getText();
        int quantity = Integer.parseInt(quantityTxt.getText());
        
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String donatedOn = dformat.format(date.getDate());
        
      //  MainJFrame mainframe = new MainJFrame();
      //  String userName = mainframe.userNameJTextField.getText();
     
     // String o="Food Organization";
    //   for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
      // {
           
        //       if(organization.getName().contains("Food Organization"))
          //    {
           
                   
              //     organization.getFoodinventory().addToInventory(shelter,location,quantity, username, donatedOn);
            //       JOptionPane.showMessageDialog(null, "Added");
                 //  populateTbl();
       //       }
       //}
      
     //  for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
       //{
           
         //      if(organization.getName().contains("Food Organization"))
           // {
           try{
               //JOptionPane.showMessageDialog(null, enterprise);
                  foodinventory.addToInventory(shelter, location, quantity, username, donatedOn);
                      // organization.getFoodinventory().addToInventory(shelter, location, quantity, username, donatedOn);
                       JOptionPane.showMessageDialog(null, quantity +" units of cloth have been donated. Thank You!");
                   populateTbl();
              //     organization.getFoodinventory().addToInventory(shelter,location,quantity, username, donatedOn);
            //       JOptionPane.showMessageDialog(null, "Added");
                 //  populateTbl();
       //       }
       //}
      
           }
           catch(NullPointerException e)
           {
               JOptionPane.showMessageDialog(null, e);
           }
            //}
       //}
    // org.getFoodinventory().addToInventory(shelter,location,quantity, username, donatedOn);
      // JOptionPane.showMessageDialog(null, "Added");
     //  JOptionPane.showMessageDialog(null, org);
      // populateTbl();
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTable foodTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField quantityTxt;
    // End of variables declaration//GEN-END:variables

    private void populateTbl() {
        
      // MainJFrame mainframe = new MainJFrame();
       //String userName = mainframe.userNameJTextField.getText();
       
       
       
     //   UserAccount useraccount= new UserAccount();
        
        DefaultTableModel model = (DefaultTableModel) foodTbl.getModel();
        model.setRowCount(0);
        //Food food=new Food();
        //for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
        
      //  for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
       //{
           
         //      if(organization.getName().contains("Food Organization"))
           //   {
                   for (Food food : foodinventory.getFoodinventory())
        {
            if(food.getProvidedby().equals(username))
            {
            Object[] row = new Object[4];
            row[0]=food.getShelter();
            row[1]=food.getLocation();
            row[2]=food.getDonatedon();
            row[3]=food.getQuantity();
            
            model.addRow(row);
            
            }
        //}
       
       
   // }
     //         }
       
    
    }

}}